#!/bin/bash

USER_ID=${USER_ID:-30000}

# Create a non-root user that will perform the actual build
id builder 2>/dev/null || \
    useradd --uid $USER_ID --create-home --home-dir /builder builder

if [[ ! -e /builder/.ssh && -d /home/user/.ssh ]]; then
  gosu builder ln -s /home/user/.ssh /builder/.ssh
fi

cd /builder
exec gosu builder "$@"
