#!/bin/bash

USER_ID=${USER_ID:-30000}

# Create a non-root user that will perform the actual build
id builder 2>/dev/null || \
    useradd --uid $USER_ID --create-home --home-dir /builder builder

dirs=".ssh downloads sstate-cache"
for dir in $dirs
do
  if [[ ! -e /builder/$dir && -d /home/user/$dir ]]; then
    gosu builder ln -s /home/user/$dir /builder/$dir
  fi
done

cd /builder
exec gosu builder "$@"
